### ISSUE TITLE
Can't reformat numbers with some other formatters around

### ISSUE THREAD

**Issue by szmeku** [szmeku/KhanAcademyDots#1]
Extension can't replace dots in such a text
`\\orange{1}.\\green{0}}`

**Comment by danielhollas** [comment]
I have a fix ready as part of Smart Translations. I will port it here once it is reviewed and merged.

**Comment by danielhollas** [comment]
This is now fixed as of db57ea6c89d3261d736c26a3ee855b2f70adbdd3. Waiting for one more change to land in TA repo and then I'll bump the plugin version and publish it.
