### ISSUE TITLE
Moving the repo?

### ISSUE THREAD

**Issue by danielhollas** [szmeku/KhanAcademyDots#15]
Hi @szmeku!

Would you mind moving this repo to [KhanovaSkola organization](https://github.com/khanovaskola/)?
It would make it a bit easier for me to maintain.

(of course your name will stay as an Author in manifest.json and I can also put it in README)

**Comment by szmeku** [comment]
Not a problem. Do you need some action from me?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by danielhollas** [comment]
Yeah, I think you need to go to the repo settings here on GitHub and transfer the ownership. Thanks! 🙇‍♂️

**Comment by szmeku** [comment]
Sure, I'll do it

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by szmeku** [comment]
I've tried to do it but I got "You don’t have the permission to create public repositories on KhanovaSkola"

First I think you have to add me to organization and give me permission to create new public repos.

Szymon

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielhollas** [comment]
@szmeku could you please try to transfer it to me as a user? `danielhollas`. I think that should work. Thanks!

**Comment by szmeku** [comment]
"Repository transfer to danielhollas requested" done.

Sorry for doing it so late.

Best,
Szymon.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielhollas** [comment]
No worries, thank you!

And thank you for starting this project, it's really helpfull to a lot of
translators.

Dne út 6. 10. 2020 2:22 odp. uživatel szmeku <notifications@github.com>
napsal:

> "Repository transfer to danielhollas requested" done.
>
> Sorry for doing it so late.
>
> Best,
> Szymon.
>
> Sent with [ProtonMail](https://protonmail.com) Secure Email.
>
> ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
> On Tuesday, October 6, 2020 1:26 PM, Daniel Hollas <
