### ISSUE TITLE
Alt + a shortcut doesn't work when you're not focused on editor

### ISSUE THREAD

**Issue by szmeku** [szmeku/KhanAcademyDots#2]
Alt + a shortcut doesn't work when you're not focused on editor

**Comment by danielhollas** [comment]
I am closing this as won't fix for now. I've been asked by Firefox reviewer to verify the origin of all external code, and it is easier to just remove `keymaster.js` since it does not work properly anyway.

**Comment by danielhollas** [comment]
Keyboard shortcut now implemented via browser, see #10.
