### ISSUE TITLE
Update Chrome extension to Manifest V3

### ISSUE THREAD

**Issue by justinmayhew** [szmeku/KhanAcademyDots#20]
We'll need to update from Manifest V2 sometime this year before support is dropped. From [The transition of Chrome extensions to Manifest V3](https://developer.chrome.com/blog/mv2-transition/):

> **January 2023**: The Chrome browser will no longer run Manifest V2 extensions. Developers may no longer push updates to existing Manifest V2 extensions.

**Comment by danielhollas** [comment]
Looks like Firefox doesn't quite support V3 yet, but that's perhaps of lesser concern.

https://www.xda-developers.com/mozilla-firefox-manifest-v3-adoption/

I have taken a crack at this and looks like the migration of this particular plugin will not be difficult, will submit a PR shortly.
