### ISSUE TITLE
select decimal mark used in your country

### ISSUE THREAD

**Issue by kristofix** [szmeku/KhanAcademyDots#4]
select decimal mark used in your country

1 234 567.89
1 234 567,89
1,234,567.89
1,234,567·89
1.234.567,89
1.234.567'89
1˙234˙567,89
1'234'567,89
1'234'567.89

**Comment by kristofix** [comment]
spacja w tym kodzie to jest {~}
przecinek {,}
' to {'}
kropka {.}                       ///czyli wsyztsko trza w wąsach pisać.

**Comment by danielhollas** [comment]
This is now supported as of commit 29e06166d885b052a71b6a40bb18bc9dd262684e vi [Translation Assistant](https://github.com/khan/translation-assistant)
Users can select their language in extensions options. As of now we support translations of multiplication, division, decimal points and thousands separators. We also translate numerals to eastern arabic numerals used in Pashto language.
