### ISSUE TITLE
funkcja wlacz/wylacz podmiane systemu dziesietnego

### ISSUE THREAD

**Issue by kristofix** [szmeku/KhanAcademyDots#6]
są zadania w ktorych ktoś moze nie chciec zmieniac systemu dziesietnego, wiec wybór systemu musi miec guzik on/off (taki sam guzik i w tym samym miejscu co cała reszta podmieniaczy)

**Comment by danielhollas** [comment]
According to Google Translate.. :-)
`there are tasks in which someone may not want to change the decimal system, so the choice of the system must have an on / off button (same button and in the same place as the rest of the changers)`

Not sure what is meant by this and the original 'Copy Source' button is always there to use. I suggest to close this...
