### ISSUE TITLE
Implement keyboard shortcut

### ISSUE THREAD

**Issue by danielhollas** [szmeku/KhanAcademyDots#9]
Apparently, it should be possible to do natively directly in the manifest.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands

Hopefully, it'll work in Chrome as well.
We should probably set the keyboard to override the default that Crowdin uses.

**Comment by danielhollas** [comment]
Started working on this on branch `keyboard-shortcut`.

Mostly done. I am getting a signal in the background script, but for some reason it is unable to send a message to the content script, with this error in Firefox console

`Could not establish connection. Receiving end does not exist.`

Note, to debug background script, click "Inspect" in firefox debugging page (about:debugging#/runtime/this-firefox) or "Inspect views on background page" in chrome. Interestingly, no errors show up in Chrome, even though it does not work there either.

**Comment by fahadashiq12** [comment]
What are the keyboard shortcuts other than Tab+shift, Arrow keys, and enter button other than this what would be the standard of putting keyboard shortcuts in react + typescript project?
